### ISSUE TITLE
Submission 6: Set and Set operations and Submission 7: Word Jumble

### ISSUE THREAD

**Issue by Sukhrobjon** [TannerYork/CS-1.3-Core-Data-Structures#6]
1. Sets: - Passing ✅
- Although you implemented set class and passing all tests., you could have used your hashtable code much better and generic way calling its functions instead of copying all functions and add union, intersection, difference, is_subset.

2. Word jumble: - Not Passing (close passing)❌
- The code is not functional, I ran both`dict_wordscramble_solver.py` and `trie_wordscramble_solver.py`
giving these errors
```
Traceback (most recent call last):
  File "dict_wordscramble_solver.py", line 26, in <module>
    scramble_solver = DictWordScrambleSolver('usrs_dict_solver.txt')
  File "dict_wordscramble_solver.py", line 11, in __init__
    self.anagram_dict = anagram_dict.load_from_file(path_to_file)
  File "/Users/sukhrobjongolibboev/Desktop/makeSchool/CS/TA-CS-1.2/CS-1.3-Core-Data-Structures/Projects/Word-Scramble-Solver/anagram_dict.py", line 22, in load_from_file
    key, words = key_value[0], key_value[1].split(',')
IndexError: list index out of range
```

**Comment by TannerYork** [comment]
Thanks for letting me know about the issue, it's fixed now. The reason I chose to recreate the hashtable code was to make it use only keys instead of the key, value pairs like in the already existing hashtable. It really doesn't make a big difference but I wanted it to stand on its own and I think sets usually don't have values and I wanted to make it as close as possible to a real set.
